core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("info.urls")),
    path("sentiment/", include("sentiment.urls")),
]

info/urls.py
from django.urls import path
from . import views

app_name = "info"

urlpatterns = [
    path("", views.index, name="index"),
]

sentiment/urls.py
from django.urls import path
from . import views

app_name = "sentiment"

urlpatterns = [
    path("", views.index, name="index"),
]

sentiment/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.http import HttpRequest, HttpResponse


def index(request: HttpRequest) -> HttpResponse:
    return HttpResponse("Hello, Dashboard")

info/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render


def index(request: HttpRequest) -> HttpResponse:
    return render(request, "info/index.html")

sentiment/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render


def index(request: HttpRequest) -> HttpResponse:
    return render(request, "sentiment/index.html")

info/templates/info/index.html
{% extends "base.html" %}
{% block title %}Info{% endblock %}

{% block content %}
<div class="vh-100 d-flex flex-column justify-content-center align-items-center text-center pb-5">
    <div class="display-6 mb-2">🌀</div>
    <h1 class="fw-light text-dark">Info</h1>
</div>
{% endblock %}

sentiment/templates/sentiment/index.html
{% extends "base.html" %}
{% block title %}Sentiment{% endblock %}

{% block content %}
<div class="vh-100 d-flex flex-column justify-content-center align-items-center text-center pb-5">
    <div class="display-6 mb-2">Привет!</div>
    <h1 class="fw-light text-dark">Sentiment</h1>
</div>
{% endblock %}

templates/_sidebar.html
<aside class="sidebar">
    <a href="{% url 'info:index' %}" 
       class="{% if request.resolver_match.url_name == 'index' %}active{% endif %}" 
       title="Hub">
        🌀
    </a>
    <a href="{% url 'sentiment:index' %}" 
       class="{% if request.resolver_match.url_name == 'index' %}active{% endif %}" 
       title="Hub">
        🌀
    </a>
</aside>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    {% include "_sidebar.html" %}
    <main class="content">
        {% block content %}{% endblock %}
    </main>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>